version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/filedata
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./client:/app
    env_file: 
    - .env.local
    depends_on:
      - server
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filedata
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: